server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # -------- USER AUTH APIs --------
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/user/auth/**

        # -------- USER CRUD APIs --------
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        # -------- AUCTION SERVICE --------
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/api/auctions/**

        # -------- BIDDING SERVICE --------
        - id: bidding-service
          uri: lb://bidding-service
          predicates:
            - Path=/api/bids/**

        # -------- TRANSACTION SERVICE --------
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**

        # -------- INVOICE SERVICE --------
        - id: invoice-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/invoices/**

      discovery:
        locator:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
