server:
  port: 8082

spring:
  application:
    name: AUCTION-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/auctiondb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: oas-secret-key-1234567890-oas-secret-key-1234567890